version: 0.0
os: linux
files:
  - source: /content
    destination: /content
  - source: /scripts
    destination: /scripts
hooks:
  AfterInstall:
    - location: /scripts/PetClinic_AfterInstall.sh
      timeout: 180
