version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
  AfterInstall:
    - location: /PetClinic_AfterInstall.sh
      timeout: 180
  ApplicationStart:
  ValidateService:

