version: '2'
services:
  config-server:
    image: leoshreyas/petclinic:config-server
    container_name: config-server
    ports:
     - 8888:8888

  discovery-server:
    image: leoshreyas/petclinic:discovery-server
    container_name: discovery-server
    links:
     - config-server
    depends_on:
      - config-server
    entrypoint: ["./wait-for-it.sh","config-server:8888","--timeout=60","--","java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
     - 8761:8761

  
